### ISSUE TITLE
Current code not working

### ISSUE THREAD

**Issue by Noah-Fuentes** [tccnw-it/FL20-COSC1436#5]
Hello, it seems that when I downloaded the code it wouldn't compile. When I searched through it, it appeared that the problems were this

Dominguez's function was declared with the parameter of an int but
was not called with an argument

 Torcious's function ended with a semi colon and was placed inside Dominguez's function

Unnecessary return 0 was added

Hope I am not the only one who can't compile this, if needed I can send the code that I was able to get working

Edited: Torcious's function was placed inside Dominguez's function, not Tourkakis's. Hope I downloaded the right one

**Comment by tccnw-it** [comment]
Send it to me. I want to take a look. Thanks.

**Comment by tccnw-it** [comment]
Updated and corrected.  Please fork again and let me know if you have issues.  (It was my fault. I merged incorrectly. Sorry)
